#Aluno: Matheus Barbosa Silva
#Professor: Daniel Corrêa
#Disciplina: Tecnologia Construção de Software
# Data: 16/10/2025

FROM nginx:alpine
# Copie os arquivos do diretório atual para o diretório padrão do Nginx
COPY . /usr/share/nginx/html